// <auto-generated />
using GarlicBread.Persistence.Document;
using GarlicBread.Persistence.Relational;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GarlicBread.Migrations
{
    [DbContext(typeof(GarlicBreadPersistenceContext))]
    partial class GarlicBreadPersistenceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("GarlicBread.Persistence.Relational.CustomizableRole", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId", "UserId", "RoleId");

                    b.ToTable("CustomizableRoles");
                });

            modelBuilder.Entity("GarlicBread.Persistence.Relational.JsonRow<GarlicBread.Persistence.Document.GuildConfig>", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<GuildConfig>("Data")
                        .HasColumnType("jsonb");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
